# isolated project where you can create resources related to your project

kind: Namespace
apiVersion: v1
metadata:
  name: expense
  labels:
    name: expense
    environment: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-namespace-quota
  namespace: expense
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"