kind: Pod
apiVersion: v1
metadata: 
  name: env-test
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: Technology
      value: k8
    - name: environment
      value: dev

# enter into container in pod and enter env to see environment variables we created above