# we are reffering the configurations given in 08-config file for this pod

apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: devopskk
    # env:
    # - name: Technology
    #   valueFrom:
    #     configMapKeyRef:
    #       name: devopskk
    #       key: Technology
    # - name: github
    #   valueFrom:
    #     configMapKeyRef:
    #       name: devopskk
    #       key: github

# loggin to pod and give env