apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data: # use base64 for encription of password - echo <username> | base64
  username: "YWRtaW4K"
  password: "S3Jpc2hAMTIxMgo="

  # To store secrets, like API tokens,passwords etc., confidential info and they are encrypted