kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    Tehnology: k8
    Environment: dev
    Component: frontend
    project: expense
  ports:
  - protocol: TCP
    port: 80 #service port
    Targetport: 80 #Target port