apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # deployment resource labels
  labels:
    name: nginx
    purpose: deployment
    tier: webtier
spec:
  replicas: 3
  # We are using Rolling Update strategy here, So no down time for application.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      name: nginx
      purpose: deployment
      tier: webtier
  # pod defination
  template:
    metadata:
      labels:
        name: nginx
        purpose: deployment
        tier: webtier
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl

# Deployment creates new pods with latest version - we updates new image, it updated new version. 
# Using RS we can't acheive this
# Deployment creates replicasets, replicasets creates pods, pods create containers
