apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-1
spec:
  affinity:
    nodeAffinity:
  # scheduler tries the asked node, but it cant schedule because it's a tainted node. 
  # since it is only preferred it can schedule on to differnt node
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - expense
  containers:
  - name: with-node-affinity
    image: nginx