apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app
  template:
    metadata: 
      labels:
        name: app
    spec:
      nodeSelector:
        node-name: expense-uat-expense-uat-Node
      containers:
      - name: nginx
        image: nginx:1.16-alpine
        ports:
        - containerPort: 80
