apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app
  template:
    metadata: 
      labels:
        name: app
    spec:
      nodeSelector: # volume in east-1c so, i can select node which is in 1c
        topology.kubernetes.io/zone: us-east-1b
      containers:
      - name: nginx
        image: nginx:1.16-alpine
        ports:
        - containerPort: 80
