apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-expense
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

#Reclaim policy
#1. Delete: after deleting pod: Volume and PV will also get deleted
#2. Retain: after deleting pod: volume and PV will be available with data
#3. Recycle: after deleting pod: volume and PV will be available but not with data